"""
AA Grapevine Subscription Articles
"""

GRAPEVINE_SUBSCRIPTION_ARTICLES = [
    {
        "id": "gv_tradition_one_1952_",
        "title": "Tradition One",
        "content": "HOME IN THE MAGAZINE TRADITION ONE\n\nhttps://www.aagrapevine.org/magazine/1952/apr/tradition-one\n\nThe first of a new series of articles explaining The Twelve Traditions . . . - Our common welfare should come first; personal recovery depends upon AA unity.\n\nThe magnificent unity of Alcoholics Anonymous is the most cherished quality our society has. Our lives, the lives of all to come, depend squarely upon it. We stay whole, or AA dies. Without unity, the great heart of AA would cease to beat, our world arteries would no longer carry the life-giving grace of God, his gift to us would be spent aimlessly. Back again in their caves, alcoholics would reproach us and say, \"What a great thing AA might have been!\"\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'god', 'recovery', 'alcoholic', 'unity', 'service'],
    },
    {
        "id": "gv_tradition_two_1952_",
        "title": "Tradition Two",
        "content": "HOME IN THE MAGAZINE TRADITION TWO\n\nhttps://www.aagrapevine.org/magazine/1952/may/tradition-two\n\nThe second of a new series of articles explaining The Twelve Traditions. . . <lbFor our group purpose there is but one ultimate authority--a loving God as he may express himself in our group conscience. Our leaders are but trusted servants--they do not go\n\nWHERE does AA get its direction? Who runs it? This too is a puzzler for every friend and newcomer. When told that our society has no president having authority to run it, no treasurer who can compel the payment of any dues, no board of directors who can cast an erring member into outer darkness, when indeed no AA can give another a directive and enforce obedience, our friends gasp and exclaim, \"This simply can't be. There must be an angle somewhere.\" These practical folk then read Tradition Two, and learn that the sole authority in AA is a loving God as he may express himself to the AA group conscience. They dubiously ask an experienced AA member if this really works. The member, sane to all appearances, immediately answers, \"Yes! It definitely does.\" The friends mutter that this looks vague, nebulous, pretty naive to them. Then they commence to watch us with speculative eyes, pick up a fragment of AA history, and soon have the solid facts and are convinced.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'god', 'experience', 'service'],
    },
    {
        "id": "gv_tradition_eight_1952_",
        "title": "Tradition Eight",
        "content": "HOME IN THE MAGAZINE TRADITION EIGHT\n\nhttps://www.aagrapevine.org/magazine/1952/dec/tradition-eight\n\nThe eighth of a new series of articles explaining The Twelve Traditions. . . <lb\"ALCOHOLICS ANONYMOUS SHOULD REMAIN FOREVER NON-PROFESSlONAL, BUT OUR SERVICE CENTERS MAY EMPLOY SPECIAL WORKERS\".\n\nALCOHOLICS ANONYMOUS will never have a professional class. We have gained some understanding of the ancient words, \"Freely ye have received, freely give.\" We have discovered that at the point of professionalism, money and spirituality do not mix. Almost no recovery from alcoholism has ever been brought about by the world's best professionals, whether medical or religious. We do not decry professionalism in other fields, but we accept the sober fact that it does not work for us. Every time we have tried to professionalize our Twelfth Step, the result has been exactly the same: our single purpose has always been defeated.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'step', 'traditions', 'recovery', 'alcoholic', 'alcoholism', 'spiritual', 'service'],
    },
    {
        "id": "gv_tradition_nine_1953_",
        "title": "Tradition Nine",
        "content": "HOME IN THE MAGAZINE TRADITION NINE\n\nhttps://www.aagrapevine.org/magazine/1953/jan/tradition-nine\n\nThe ninth of a new series of articles explaining The Twelve Traditions <lb<emphasis type=\"italic\">\"AA, AS SUCH, OUGHT NEVER BE ORGANIZED; BUT WE MAY CREATE SERVICE BOARDS OR COMMITTEES DIRECTLY RESPONSIBLE TO THOSE THEY SERVE.\"</emphasis>\n\nWHEN Tradition Nine was first written, it said that \"Alcoholics Anonymous needs the least possible organization.\" In years since then, we have changed our minds about that. Today we are able to say with assurance that Alcoholics Anonymous. . . AA as a whole. . .should never be organized at all. Then, in seeming contradiction, we proceed to create special service boards and committees which in themselves are organized. How, then, can we have an unorganized movement which can and does create a service organization for itself? Scanning this puzzler, people say, \"What do they mean, no organization?!\"\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'alcoholic', 'service'],
    },
    {
        "id": "gv_tradition_ten_1953_",
        "title": "Tradition Ten",
        "content": "HOME IN THE MAGAZINE TRADITION TEN\n\nhttps://www.aagrapevine.org/magazine/1953/feb/tradition-ten\n\nThe tenth of a new series of articles explaining The Twelve Traditions<lb \"ALCOHOLICS ANONYMOUS HAS NO OPINION ON OUTSIDE ISSUES; HENCE THE AA NAME OUGHT NEVER BE DRAWN INTO PUBLIC CONTROVERSY.\n\nNEVER since it began has Alcoholics Anonymous been divided by a major controversial issue. Nor has our fellowship ever publicly taken sides on any question in an embattled world. This, however, has been no earned virtue. It could almost be said that we were born with it, for as one old-timer recently declared, \"Practically never have I heard a heated religious, political or reform argument among AA members. So long as we don't argue these matters privately, it's a cinch we never shall publicly.\"\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'alcoholic', 'fellowship', 'service'],
    },
    {
        "id": "gv_tradition_eleven_1953_",
        "title": "Tradition Eleven",
        "content": "HOME IN THE MAGAZINE TRADITION ELEVEN\n\nhttps://www.aagrapevine.org/magazine/1953/mar/tradition-eleven\n\nThe eleventh of a series of articles explaining The Twelve Traditions <lb \"OUR\n\nWITHOUT its legions of well-wishers, AA could never have grown as it has. Throughout the world, immense and favorable publicity of every description has been the principal means of bringing alcoholics into our fellowship. In AA offices, clubs, and homes telephones ring constantly. One voice says, \"I read a piece in the newspapers. . .\", another, \"We heard a radio program. . .\", and still another, \"We saw a moving picture. . .\", or, \"We saw something about AA on television. . . .\" It is no exaggeration to say that half of AA's membership has been led to us through channels like these.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'alcoholic', 'fellowship', 'service'],
    },
    {
        "id": "gv_tradition_twelve_1953_",
        "title": "Tradition Twelve",
        "content": "HOME IN THE MAGAZINE TRADITION TWELVE\n\nhttps://www.aagrapevine.org/magazine/1953/apr/tradition-twelve\n\nThe last of a series of articles explaining The Twelve Traditions <lb<emphasis type=\"italic\">\"Anonymity is the spiritual foundation of all our Traditions, ever reminding us to place principles above personalities.\"</emphasis>\n\nTHE spiritual substance of anonymity is sacrifice. Because AA's Twelve Traditions repeatedly ask us to give up personal desires for the common good, we realize that the sacrificial spirit--well symbolized by anonymity--is the foundation of them all. It is AA's proved willingness to make these sacrifices that gives people their high confidence in our future.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "tradition",
        "keywords": ['tradition', 'traditions', 'spiritual', 'service', 'anonymity', 'willingness'],
    },
    {
        "id": "gv_step_6_revisited",
        "title": "The Twelve Steps Revisited/step 6",
        "content": "HOME IN THE MAGAZINE THE TWELVE STEPS REVISITED/STEP 6\n\nhttps://www.aagrapevine.org/magazine/1962/feb/twelve-steps-revisitedstep-6\n\nThe Twelve Steps Revisited/step 6\n\nBY: J. E. | GUILFORD, CONNECTICUT\n\nWere entirely ready to have God remove all these defects of character\n\nIN commenting on Step Six, the Big Book simply dumps the matter in your lap, wrapping up the whole business in one short paragraph. It asks whether we're willing to be rid of the things we've admitted are objectionable. \"If we still cling to something we will not let go,\" it says, \"we ask God to help us to be willing.\" With that, it leaves us on our own.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "step",
        "keywords": ['step', 'steps', 'god', 'defects', 'character', 'service'],
    },
    {
        "id": "gv_step_12_revisited",
        "title": "The Twelve Steps Revisited/Step 12",
        "content": "HOME IN THE MAGAZINE THE TWELVE STEPS REVISITED/STEP 12\n\nhttps://www.aagrapevine.org/magazine/1963/oct/twelve-steps-revisitedstep-12\n\nThe Twelve Steps Revisited/Step 12\n\nBY: J. E. | GUILFORD, CONNECTICUT\n\nHaving had a spiritual awakening as the result of these Steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.\n\nOFTEN, if we keep our ears open, we have a chance to learn something from someone much younger in the movement than ourselves. Such an opportunity came to me a couple of months ago. A visiting AA from the midwest, \"in\" a relatively short time, got to talking about difficult Twelfth Step cases. I told him about one of mine, a neighbor who had recently called to ask what he could do about his drinking \"short of joining AA.\" I had given him my story and said that in my own case nothing but AA had worked.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "step",
        "keywords": ['step', 'steps', 'alcoholic', 'spiritual', 'unity', 'service'],
    },
    {
        "id": "gv_8th_step_1971_",
        "title": "8th Step",
        "content": "https://www.aagrapevine.org/magazine/1971/jan/8th-step\n\nBY: F. M. | NEW CANAAN, CONNECTICUT\n\nMade a list of all persons we had harmed and became willing to make amends to them all. - This series on the Twelve Steps is written by twelve members of A A, each interpreting one of the Steps as he sees it.\n\nI CHOSE this Step to write about because it's the toughest one for me. I've had one hell of a time with the state of willingness. For, in order to be willing to make amends to others, you must first forgive yourself and be ready to make amends to yourself. And I am just beginning to see this in broad daylight. Formerly, I was half-aware that I had not really forgiven myself. It was what I call gauze-curtain, awareness; you see the problem dimly, as if through a veil, but you can't really formulate it. I think that many of us in AA have a hard time with self-acceptance. And the result is misery, whether it takes the form of repeated slips, depressions or psychosomatic illness, or failure in business or human relationships.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "step",
        "keywords": ['step', 'steps', 'amends', 'service', 'willingness'],
    },
    {
        "id": "gv_taking_that_first_step_2020_",
        "title": "Taking That First Step",
        "content": "HOME IN THE MAGAZINE TAKING THAT FIRST STEP\n\nhttps://www.aagrapevine.org/magazine/2020/nov/taking-first-step\n\nAided by the “limitless hope and boundless grace” of AA, she took the Step that changed her life\n\nI often hear at meetings that Step One is the only Step that must be practiced perfectly. But is practicing perfectly oxymoronic? As a perfectionist and as an alcoholic, I had a problem with this. Fortunately, my sponsor was a careful reader and led me to the Twelve and Twelve. It reads: “Only Step One, where we made the 100% admission that we were powerless over alcohol, can be practiced with complete perfection.” The Big Book also tells us: “There must be no reservation of any kind, nor any lurking notion that someday we will be immune to alcohol.” This frightened me when I first got sober. I was certainly at the jumping off point but believing in the program required a huge leap of faith. My faith was barely audible, and the disease and I had a rich history. I wanted recovery more than I wanted to drink—but just by a nearly imperceptible hair. A civil war ensued.\n\nCall 800 631-6025 (English), 800 640-8781 (Spanish), 212-870-3456 (French) or email: customerservice@aagrapevine.org",
        "source": "AA Grapevine Magazine",
        "content_type": "step",
        "keywords": ['step', 'sponsor', 'recovery', 'alcoholic', 'powerless', 'service'],
    },
    {
        "id": "gv_archive_same_problem_for_all",
        "title": "Same Problem for All",
        "content": "HOME IN THE MAGAZINE SAME PROBLEM FOR ALL\n\nhttps://www.aagrapevine.org/magazine/1945/sep/same-problem-all\n\n(Editor's Note: The war's end is only the beginning of a personal struggle for some of the men now coming home. This article is by one member of A.A., a veteran of the last war, who began his own drinking career largely as a result of boredom with readjustment to civilian life and because he missed the Army comradeship. It is a brief treatment of a complex subject and any ideas or comments from Grapevine readers will be welcomed by the staff.)\n\nYou must have an active online AA Grapevine subscription to access full stories and audio.",
        "source": "AA Grapevine Magazine",
        "content_type": "personal_story",
        "keywords": ['personal_story'],
    },
    {
        "id": "gv_archive_ours_not_to_judge",
        "title": "Ours Not to Judge",
        "content": "https://www.aagrapevine.org/magazine/1946/aug/ours-not-judge\n\nThe first edition of the book Alcoholics Anonymous makes this brief statement about membership: \"The only requirement for membership is an honest desire to stop drinking. We are not allied with any particular faith, sect or denomination nor do we oppose anyone. We simply wish to be helpful to those who are afflicted.\" This expressed our feeling as of 1939, the year our book was published.\n\nYou must have an active online AA Grapevine subscription to access full stories and audio.",
        "source": "AA Grapevine Magazine",
        "content_type": "membership",
        "keywords": ['membership', 'alcoholic'],
    },
    {
        "id": "gv_archive_humility_for_today",
        "title": "Humility for Today",
        "content": "https://www.aagrapevine.org/magazine/1961/jun/humility-today\n\nThere can be no absolute humility for us humans. At best, we can only glimpse the meaning and splendor of such a perfect ideal. As the book \"Alcoholics Anonymous\" says: \"We are not saints. . .we claim spiritual progress rather than spiritual perfection.\" Only God Himself can manifest in the Absolute; we human beings must needs live and grow in the domain of the relative. We seek humility for today.\n\nYou must have an active online AA Grapevine subscription to access full stories and audio.",
        "source": "AA Grapevine Magazine",
        "content_type": "spiritual",
        "keywords": ['spiritual', 'god', 'alcoholic', 'humility'],
    },
]
